#pragma once

enum class NodeType {
    PROGRAM, RUN_BLOCK, VAR_DECL, INT_LIT, IDENT, BOOL_LIT, DECIMAL_LIT, CHAR_LIT,
    STRING_LIT,NULL_LIT, CAST_EXPR,
    UNARY_EXPR, GROUPED_EXPR, ARRAY_DECL, BINARY_EXPR, BETWEEN_EXPR, TERNARY_EXPR,
    BLOCK, IF_STMT,SWITCH_STMT, BREAK_STMT, WHILE_STMT, DOWHILE_STMT, FOR_STMT, CONTINUE_STMT, PASS_STMT,
    ASSIGNMENT_EXPR, INDEX_EXPR,
    FUNC_DEF,RETURN_STMT,CALL_EXPR, ENUM_DECL, FOR_IN_STMT, IMPORT_STMT, EXTERN_DECL,
};
struct ASTNode {
    NodeType type;
    int line;
    virtual ~ASTNode() = default;
};

