#pragma once

/*

   Bery Symantic Analyzer,

   It traverse the AST after it is fully generated by the Parser.
   and checks MEANING. analyze() is main function here.

   it operates in two passes - 
      1. collects all functions, externs, and enums declaration into the global table
      2. walks every node and checks if
         - varible is declared before it's use.
         - there are no re-declaration of varibles.
         - maintaining break and continue only inside loops.
         - return only inside the functions, and with correct type.
         - function calling and declaration should have same argument count.

   Symantic Analzyer's type correctness is delegated to TypeChecker.


*/

#include <memory>
#include "../parser/ast/node.h"
#include "../parser/ast/classes.h"
#include "symboltable.h"
#include "typechecker.h"
#include <unordered_map>

class SemanticAnalyzer {
public:
   SemanticAnalyzer(ASTNode* root);
   void analyze();
   bool hasErrors();
   SymbolTable symbolTable;


private:
   ASTNode* root;
   TypeChecker typeChecker; 
   bool errors;

   // @blocks
   void analyzeBlock(ASTNode* node);
   void analyzeNode(ASTNode* node);

   // @conditionals
   void analyzeIfStmt(ASTNode* node);
   void analyzeSwitchStmt(ASTNode* node);

   // @loops
   int loopOrSwitchDepth = 0;
   int loopDepth = 0;
   void analyzeWhileStmt(ASTNode* node);
   void analyzeDoWhileStmt(ASTNode* node);
   void analyzeForInStmt(ASTNode* node);
   void analyzeForStmt(ASTNode* node);

   // @declarations
   void analyzeVarDecl(ASTNode* node);
   void analyzeArrayDecl(ASTNode* node);
   void analyzeEnumDecl(ASTNode* node);

   // @controlflow
   void analyzeBreakStmt(ASTNode* node);
   void analyzeContinueStmt(ASTNode* node);

   // @functions
   std::unordered_map<std::string, FunctionSignature> functions;
   std::string currentFunctionReturnType = "";
   void analyzeFuncDef(ASTNode* node);
   void analyzeReturnStmt(ASTNode* node);

   // @oop
   std::unordered_map<std::string, ClassDefNode*> classes;
   void analyzeClassDecl(ASTNode* node);
};
