#pragma once
#include <string>

enum class TokenType {
    //@Tokens: type tokens
    TOKEN_INT, TOKEN_BOOL, TOKEN_FLOAT, TOKEN_BIGINT, TOKEN_DOUBLE, TOKEN_CHAR, TOKEN_STRING,
    
    TOKEN_IDENT, TOKEN_EQUAL, TOKEN_INT_LIT, TOKEN_SEMICOLON,
    TOKEN_EOF, TOKEN_RUN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_CONST, TOKEN_COMMA, 
    TOKEN_TRUE, TOKEN_FALSE ,
     TOKEN_DECIMAL_LIT,
    
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
     TOKEN_CHAR_LIT,
     TOKEN_STRING_LIT, 

    //@optrs
    TOKEN_LPARAN, TOKEN_RPARAN, TOKEN_MINUS, TOKEN_INC, TOKEN_DEC, TOKEN_BANG, TOKEN_TILDE,
    TOKEN_STAR, TOKEN_FSLASH, TOKEN_PERCENT, TOKEN_POWER, TOKEN_LSHIFT, TOKEN_RSHIFT,
    TOKEN_PLUS,
    TOKEN_NULL,
    TOKEN_CARET, TOKEN_AMPERSAND, TOKEN_PIPE, TOKEN_BETWEEN, TOKEN_NOT_BETWEEN,
    TOKEN_EQUAL_EQUAL,TOKEN_NOT_EQUAL,TOKEN_LTHAN,TOKEN_GTHAN,TOKEN_GTEQUAL,TOKEN_LTEQUAL,
    TOKEN_AND, TOKEN_OR,
    TOKEN_QUESTION, TOKEN_COLON,
    TOKEN_IF, TOKEN_ELSE,
    TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,TOKEN_BREAK, TOKEN_FOR,TOKEN_IN, TOKEN_WHILE, TOKEN_DOWHILE, TOKEN_CONTINUE, TOKEN_PASS,
    TOKEN_ADD_ASSIGN,TOKEN_SUB_ASSIGN,TOKEN_MUL_ASSIGN,TOKEN_DIV_ASSIGN,TOKEN_DSTAR_ASSIGN,TOKEN_MODULE_ASSIGN,
    TOKEN_AND_ASSIGN,TOKEN_OR_ASSIGN,TOKEN_XOR_ASSIGN,TOKEN_LSHIFT_ASSIGN,TOKEN_RSHIFT_ASSIGN,

    //function
    TOKEN_FUNC,TOKEN_RETURN,TOKEN_NONE,TOKEN_ARROW, TOKEN_ENUM, TOKEN_DOT, TOKEN_RANGE, TOKEN_IMPORT

};

struct Token {
    TokenType type;
    std::string lexeme;
    int line;
};
