#pragma once
#include <string>

enum class TokenType {
    TOKEN_INT, TOKEN_IDENT, TOKEN_EQUAL, TOKEN_INT_LIT, TOKEN_SEMICOLON,
    TOKEN_EOF, TOKEN_RUN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_CONST, TOKEN_COMMA, TOKEN_BOOL,
    TOKEN_TRUE, TOKEN_FALSE ,
    TOKEN_FLOAT, TOKEN_DECIMAL_LIT,
    TOKEN_BIGINT,
    TOKEN_DOUBLE,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_CHAR, TOKEN_CHAR_LIT,

    //@optrs
    TOKEN_LPARAN, TOKEN_RPARAN, TOKEN_MINUS, TOKEN_INC, TOKEN_DEC, TOKEN_BANG, TOKEN_TILDE,
    TOKEN_STAR, TOKEN_FSLASH, TOKEN_PERCENT, TOKEN_POWER,
    TOKEN_PLUS

};

struct Token {
    TokenType type;
    std::string lexeme;
    int line;
};
